services:
  db:
    image: mariadb:10.9
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle      
    volumes:
      - desafio_data:/var/lib/mysql 
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: app 
    command: dockerize -wait tcp://db:3306 -timeout 60s node src/index.js
    volumes:       
      - .:/app  
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network    
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  desafio_data:
